name: "Generate PR with AI"
description: "Generate PR body using OpenAI GPT (markdown only, with retries)"

inputs:
  openai_api_key:
    required: true
  stats_file:
    required: false
    default: "/tmp/stats.txt"
  files_file:
    required: false
    default: "/tmp/files.txt"
  diff_file:
    required: false
    default: "/tmp/diff.txt"

outputs:
  body:
    description: "Generated PR body in markdown format"
    value: "${{ steps.gen.outputs.body }}"

runs:
  using: "composite"
  steps:
    - name: "Generate PR Markdown"
      id: "gen"
      shell: "bash"
      env:
        OPENAI_API_KEY: "${{ inputs.openai_api_key }}"
      run: |
        set -euo pipefail

        # -----------------------------
        # 1) Prompt (MARKDOWN ONLY)
        # -----------------------------
        cat > /tmp/prompt.txt << 'EOF'
        You are an expert software engineer writing a professional Pull Request in Korean.

        IMPORTANT:
        - Analyze ALL changes comprehensively (Stats → New Files → Diff)
        - Pay special attention to newly added files and architectural changes

        OUTPUT RULES:
        - Return ONLY Markdown (no JSON, no code fences)
        - Use ###, #### for subsections, code blocks (```), lists, quotes (>)
        - Write naturally and professionally like a senior developer

        PR BODY STRUCTURE (4 sections):

        > 🤖 **이 PR은 OpenAI GPT-5-mini를 사용하여 자동 생성되었습니다.**

        ## 요약
        핵심 변경사항과 목적을 1-2문장으로 간결하게 작성

        ## 주요 변경 사항
        기능/모듈 단위로 작성 (파일명 나열 금지):
        - ### 또는 #### 서브섹션으로 기능별 구분
        - 각 기능의 핵심만 간략히 설명
        - 불릿 포인트로 세부사항 정리

        예시:
        ### 1. 새로운 인증 시스템
        - JWT 기반 토큰 인증
        - 리프레시 토큰 자동 갱신

        ## 상세 구현 내용
        **섹션은 반드시 유지, 아래 항목은 해당사항만 작성**

        필요시 ### 서브섹션 사용하여 구조화:
        - **새 기술/라이브러리**: 사용법, 설정 방법, 코드 예시 필수
        - **아키텍처/구조 변경**: 변경 이유와 설계 설명
        - **복잡한 로직**: 알고리즘 설명
        - **기술적 결정**: 선택 배경과 이유
        - **필요 설정**: 환경변수, 시크릿, 추가 설정 안내

        모두 없으면 "특이사항 없음" 한 줄만 작성

        ## 트러블 슈팅
        구현 중 발생한 문제와 해결 방법
        없으면: "트러블슈팅 사항 없음"

        **금지사항:**
        추가 섹션(테스트 계획, 리뷰 포인트 등) 절대 금지

        --- Stats ---
        EOF
        cat "${{ inputs.stats_file }}" >> /tmp/prompt.txt
        cat >> /tmp/prompt.txt << 'EOF'

        --- Files ---
        EOF
        cat "${{ inputs.files_file }}" >> /tmp/prompt.txt
        cat >> /tmp/prompt.txt << 'EOF'

        --- Diff ---
        EOF
        cat "${{ inputs.diff_file }}" >> /tmp/prompt.txt

        PROMPT="$(cat /tmp/prompt.txt)"
        echo "📝 Prompt size: $(printf "%s" "$PROMPT" | wc -c | tr -d ' ') characters"

        # -----------------------------
        # 2) Call OpenAI with retries
        # -----------------------------
        BODY=""

        for i in {1..3}; do
          echo "🔄 OpenAI API 호출 시도 $i/3"

          RESPONSE="$(curl -sS https://api.openai.com/v1/responses \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "{
              \"model\": \"gpt-5-mini\",
              \"input\": [
                {\"role\": \"system\", \"content\": \"Write a GitHub Pull Request body in Korean Markdown. Return markdown only.\"},
                {\"role\": \"user\", \"content\": $(printf \"%s\" \"$PROMPT\" | jq -Rs .)}
              ],
              \"max_output_tokens\": 4096
            }")"

          # API error 체크
          if echo "$RESPONSE" | jq -e '.error' >/dev/null 2>&1; then
            echo "❌ API Error: $(echo "$RESPONSE" | jq -r '.error.message // .error')"
            [ $i -lt 3 ] && sleep $((i * 2))
            continue
          fi

          # Markdown 본문 추출
          BODY="$(echo "$RESPONSE" | jq -r '[.output[]?.content[]?.text // ""] | join("")')"

          if [ -n "$BODY" ] && [ "$BODY" != "null" ]; then
            echo "✅ PR 생성 완료"
            break
          fi

          echo "⚠️  본문 추출 실패 - 재시도 중"
          [ $i -lt 3 ] && sleep $((i * 2))
        done

        if [ -z "$BODY" ] || [ "$BODY" = "null" ]; then
          echo "❌ OpenAI API 호출 실패(본문 비어있음)"
          exit 1
        fi

        # -----------------------------
        # 3) Use markdown AS-IS
        # -----------------------------
        echo "body<<EOF" >> "$GITHUB_OUTPUT"
        printf "%s\n" "$BODY" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
