name: "Generate PR with AI"
description: "Generate PR body using OpenAI GPT (markdown only, with retries)"

inputs:
  openai_api_key:
    required: true
  stats_file:
    required: false
    default: "/tmp/stats.txt"
  files_file:
    required: false
    default: "/tmp/files.txt"
  diff_file:
    required: false
    default: "/tmp/diff.txt"

outputs:
  body:
    description: "Generated PR body in markdown format"
    value: "${{ steps.gen.outputs.body }}"

runs:
  using: "composite"
  steps:
    - name: "Generate PR Markdown"
      id: "gen"
      shell: "bash"
      env:
        OPENAI_API_KEY: "${{ inputs.openai_api_key }}"
      run: |
        set -euo pipefail

        # -----------------------------
        # 1) Prompt (MARKDOWN ONLY)
        # -----------------------------
        cat > /tmp/prompt.txt << 'EOF'
        You are an expert software engineer writing a professional Pull Request in Korean.

        IMPORTANT:
        - Analyze ALL changes in the diff comprehensively.
        - Pay special attention to newly added files and major architectural changes.

        OUTPUT RULES (VERY IMPORTANT):
        - Return ONLY Markdown.
        - Do NOT return JSON.
        - Do NOT wrap output in code fences.
        - The content will be used AS-IS as the GitHub PR body.

        **마크다운 작성 규칙:**
        - ###, #### 등 다양한 헤딩 레벨을 사용하여 계층적 구조 표현
        - 코드 블록(```), 인용문(>), 리스트 등 마크다운 문법을 적극 활용
        - 보기 좋게 구조화하여 가독성 향상

        PR BODY STRUCTURE (정확히 아래 4개 섹션만):

        > 🤖 **이 PR은 Open AI GPT-5-mini를 사용하여 자동 생성되었습니다.**

        ## 요약
        변경사항의 핵심과 목적을 1-2문장으로 간결하게

        ## 주요 변경 사항
        기능/모듈 단위로 **중요한 변경사항만** 작성 (파일 나열 금지)
        필요시 ### 또는 #### 서브섹션으로 구분

        ## 상세 구현 내용
        이해에 필요한 **핵심 내용만** 작성:
        - 아키텍처나 구조 변경이 있다면 설명
        - 중요한 로직이나 알고리즘이 있다면 설명
        - 특별한 기술적 결정이 있다면 그 이유와 함께 설명
        - 중요하지 않은 내용은 생략
        - 필요시 ### 또는 #### 서브섹션으로 구분

        ## 트러블 슈팅
        - 구현 중 발생한 문제와 해결 방법이 있다면 작성
        - 없으면: "- 트러블슈팅 사항 없음"

        **절대 추가 금지:**
        주의사항, 권고사항, 알려진 이슈, 리뷰 포인트, 테스트 계획 등의 추가 섹션

        분석 우선순위:
        1) Stats 2) Files(신규 파일 우선) 3) Diff

        --- Stats ---
        EOF
        cat "${{ inputs.stats_file }}" >> /tmp/prompt.txt
        cat >> /tmp/prompt.txt << 'EOF'

        --- Files ---
        EOF
        cat "${{ inputs.files_file }}" >> /tmp/prompt.txt
        cat >> /tmp/prompt.txt << 'EOF'

        --- Diff ---
        EOF
        cat "${{ inputs.diff_file }}" >> /tmp/prompt.txt

        PROMPT="$(cat /tmp/prompt.txt)"
        echo "📝 Prompt size: $(printf "%s" "$PROMPT" | wc -c | tr -d ' ') characters"

        # -----------------------------
        # 2) Call OpenAI with retries
        # -----------------------------
        BODY=""

        for i in {1..3}; do
          echo "🔄 OpenAI API 호출 시도 $i/3"

          RESPONSE="$(curl -sS https://api.openai.com/v1/responses \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "{
              \"model\": \"gpt-5-mini\",
              \"input\": [
                {\"role\": \"system\", \"content\": \"Write a GitHub Pull Request body in Korean Markdown. Return markdown only.\"},
                {\"role\": \"user\", \"content\": $(printf \"%s\" \"$PROMPT\" | jq -Rs .)}
              ],
              \"max_output_tokens\": 4096
            }")"

          # API error 체크
          if echo "$RESPONSE" | jq -e '.error' >/dev/null 2>&1; then
            echo "❌ API Error: $(echo "$RESPONSE" | jq -r '.error.message // .error')"
            [ $i -lt 3 ] && sleep $((i * 2))
            continue
          fi

          # Markdown 본문 추출
          BODY="$(echo "$RESPONSE" | jq -r '[.output[]?.content[]?.text // ""] | join("")')"

          if [ -n "$BODY" ] && [ "$BODY" != "null" ]; then
            echo "✅ PR 생성 완료"
            break
          fi

          echo "⚠️  본문 추출 실패 - 재시도 중"
          [ $i -lt 3 ] && sleep $((i * 2))
        done

        if [ -z "$BODY" ] || [ "$BODY" = "null" ]; then
          echo "❌ OpenAI API 호출 실패(본문 비어있음)"
          exit 1
        fi

        # -----------------------------
        # 3) Use markdown AS-IS
        # -----------------------------
        echo "body<<EOF" >> "$GITHUB_OUTPUT"
        printf "%s\n" "$BODY" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
